name 'lfisher47-stig_generic'
version '0.0.5'
author 'lfisher47'
summary 'Generic STIG rule enforcement'
description 'Generic STIG rule enforcement'
license 'GNU GPL 2.0'
source 'git://github.com/lfisher47/puppet-stig_generic'
project_page 'https://github.com/lfisher47/puppet-stig_generic'
